name: deepicedrain
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - rapidsai::cuml=0.15.0[md5=09125e971304f6020788d3da4bf1ef55]
  - rapidsai::cuspatial=0.15.0[md5=728b9006370db38fa4fc3d0fe19fc8c3]
  - conda-forge::geos=3.8.1[md5=7282fbe0c036bacad959c03c05a7eb9a]
  - conda-forge/label/dev::gmt=6.2.0.dev0+a1a189c[md5=915cb603613887002b58e09859aaac82]
  - conda-forge::gxx_linux-64=7.5.0[md5=36f3b65563c9264b6d1e04369f0456ba]
  - conda-forge::nodejs=13.13.0[md5=cf25f8cee7aad7f417980872d34d8fd6]
  - conda-forge::parallel=20200522[md5=8fa06db0afc1e7b1f136277557a4b65e]
  - conda-forge::pip=20.1.1[md5=5e42afe5672d5baf3d9d2260239aa923]
  - conda-forge::poetry=1.0.9[md5=8f0019c82ec6795bcc84fc711b1d72e4]
  - conda-forge::proj=6.3.1[md5=dc4391dda7677c7299248d9754672526]
  - conda-forge::python=3.8.3[md5=05f7e9adaf1f49dad884929ab0245ddc]
  - conda-forge::snappy=1.1.8[md5=83f1dc295c711bdbaf97e1f3bedf2f52]
