name: deepicedrain
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - rapidsai::cuml=0.16.0[md5=860bf18db9682fbf2b679e33b2163fe9]
  - rapidsai::cuspatial=0.16.0[md5=135a197274994aae324c439c19431ba7]
  - conda-forge::geos=3.8.1[md5=7282fbe0c036bacad959c03c05a7eb9a]
  - conda-forge/label/dev::gmt=6.2.0.dev4+92c5676[md5=a60d72bf5a32f10e96c4ad23df5e8f28]
  - conda-forge::gxx_linux-64=7.5.0[md5=36f3b65563c9264b6d1e04369f0456ba]
  - conda-forge::nodejs=13.13.0[md5=cf25f8cee7aad7f417980872d34d8fd6]
  - conda-forge::parallel=20200522[md5=8fa06db0afc1e7b1f136277557a4b65e]
  - conda-forge::pip=20.2.3[md5=2a473e697f17443a8647c3d7d22043d3]
  - conda-forge::poetry=1.1.2[md5=bb2c94a77e5520311c6226534c1b24cb]
  - conda-forge::proj=7.0.0[md5=6c84860aef0eeb9a547dbbb849e964fe]
  - conda-forge::python=3.8.6[md5=dd65401dfb61ac030edc0dc4d15c2c51]
  - conda-forge::snappy=1.1.8[md5=83f1dc295c711bdbaf97e1f3bedf2f52]
