name: deepicedrain
channels:
  - conda-forge
dependencies:
  - conda-forge::geos=3.8.1[md5=7282fbe0c036bacad959c03c05a7eb9a]
  - conda-forge::gmt=6.0.0[md5=aaaa6cf3f64bd4a9ea0a9e98f615ef55]
  - conda-forge::gxx_linux-64=7.5.0[md5=c6afca6a2bfe1ea0ff5566d300460501]
  - conda-forge::nodejs=13.13.0[md5=cf25f8cee7aad7f417980872d34d8fd6]
  - conda-forge::parallel=20200522[md5=8fa06db0afc1e7b1f136277557a4b65e]
  - conda-forge::pip=20.1.1[md5=5e42afe5672d5baf3d9d2260239aa923]
  - conda-forge::poetry=1.0.5[md5=171d7400c2aae11e3a3a30055de3eaa7]
  - conda-forge::proj=6.3.1[md5=dc4391dda7677c7299248d9754672526]
  - conda-forge::python=3.8.3[md5=05f7e9adaf1f49dad884929ab0245ddc]
  - conda-forge::snappy=1.1.8[md5=a263bb8916842a5881b1168e3cdcfea3]
